language: node_js
node_js:
- stable
services:
  - postgresql
addons:
  postgresql: "9.5"
cache:
  directories:
  - node_modules
before_script:
- npm install
- psql -c 'DROP DATABASE IF EXISTS test;' -U postgres
- psql -c 'CREATE DATABASE test;' -U postgres
script:
- npm run coverage:coveralls
